// <auto-generated />
using System;
using DVar.PList.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DVar.PList.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240522230238_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DVar.PList.Domain.Entities.CustomColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PricelistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PricelistId");

                    b.ToTable("CustomColumns");
                });

            modelBuilder.Entity("DVar.PList.Domain.Entities.Pricelist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pricelists");
                });

            modelBuilder.Entity("DVar.PList.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PricelistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PricelistId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DVar.PList.Domain.Entities.ProductCustomValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomColumnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductCustomValues");
                });

            modelBuilder.Entity("DVar.PList.Domain.Entities.CustomColumn", b =>
                {
                    b.HasOne("DVar.PList.Domain.Entities.Pricelist", null)
                        .WithMany("CustomColumns")
                        .HasForeignKey("PricelistId");
                });

            modelBuilder.Entity("DVar.PList.Domain.Entities.Product", b =>
                {
                    b.HasOne("DVar.PList.Domain.Entities.Pricelist", null)
                        .WithMany("Products")
                        .HasForeignKey("PricelistId");
                });

            modelBuilder.Entity("DVar.PList.Domain.Entities.Pricelist", b =>
                {
                    b.Navigation("CustomColumns");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
